### ISSUE TITLE
Preprocessing is not working on the foo.md file that we edit, but on the orig/foo.md . 

### ISSUE THREAD

**Issue by akaped** [mmagnus/geekbook#13]
I have this issue for you :) 
I think this is why your note's img/foo.png are not correctly displayed when you watch them from your phone.  This happens to me with dropbox images. My function replaces perfectly the dl=0 with raw=1 on my image link ; it is displayed magnificently on GeekBook, but if I open the foo.md with another editor (  MacDown ) they are not displayed correctly because foo.md still contains dl=0. 

We are not doing preprocessing on the foo.md file that we edit, but on the orig/foo.md. 

I'm thinking if it is possible to do pre processing on the foo.md without breaking the rest.

**Comment by mmagnus** [comment]
Thank for you thoughts. Unfortunately in my case there is a different problem. It seems that Byword does not see my imgs/ folder in the notes/ folder. Byword sync markdown but now imgs files that should go along with them. Byword properly showed imgs with I drag-and-dropped them to Byword using iTunes, but this is not the most seemless way to sync my notes :-)

**Comment by akaped** [comment]
At least I learnt how to submit an issue. :)

**Comment by mmagnus** [comment]
:-) it might be useful for others, in the future, when we conquer the world!
