### ISSUE TITLE
page-index-update don't really use the specified theme.

### ISSUE THREAD

**Issue by akaped** [mmagnus/geekbook#71]
Giving the command geekbook -u, all the pages are updated using the theme specified in the local_config.py, but when there is a single page update, like saving a change in a .md file, the html is generated using the default theme.

**Comment by mmagnus** [comment]
![screen shot 2017-11-03 at 9 01 49 pm](https://user-images.githubusercontent.com/118740/32393564-49dd636e-c0da-11e7-9fea-7009af2c8823.png)

works for me ;-) 

It seems that the index itself is not updated with -u. To do at some point.
