### ISSUE TITLE
Dead link in Get Started

### ISSUE THREAD

**Issue by janekmi** [mmagnus/geekbook#91]
[Get Started][start] and [Out | Read][read] have a dead link:
- https://addons.mozilla.org/en-US/firefox/addon/auto-reload/?src=api

[start]: https://github.com/mmagnus/geekbook/blob/master/docs/source/getstarted.rst
[read]: https://github.com/mmagnus/geekbook/blob/master/docs/source/view.rst

**Comment by mmagnus** [comment]
Thanks! The dead links removed. :-)
